//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSNestedScrollViewPlugin\src\main\java\com\ashera\nestedscrollview\NestedScrollViewPlugin.java
//

#include "J2ObjC_source.h"
#include "NestedScrollViewImpl.h"
#include "NestedScrollViewPlugin.h"
#include "WidgetFactory.h"


@implementation ASNestedScrollViewPlugin

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASNestedScrollViewPlugin_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)initPlugin {
  ASNestedScrollViewPlugin_initPlugin();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initPlugin);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _ASNestedScrollViewPlugin = { "NestedScrollViewPlugin", "com.ashera.nestedscrollview", NULL, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ASNestedScrollViewPlugin;
}

@end

void ASNestedScrollViewPlugin_init(ASNestedScrollViewPlugin *self) {
  NSObject_init(self);
}

ASNestedScrollViewPlugin *new_ASNestedScrollViewPlugin_init() {
  J2OBJC_NEW_IMPL(ASNestedScrollViewPlugin, init)
}

ASNestedScrollViewPlugin *create_ASNestedScrollViewPlugin_init() {
  J2OBJC_CREATE_IMPL(ASNestedScrollViewPlugin, init)
}

void ASNestedScrollViewPlugin_initPlugin() {
  ASNestedScrollViewPlugin_initialize();
  ASWidgetFactory_register__WithASIWidget_(new_ASNestedScrollViewImpl_init());
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASNestedScrollViewPlugin)
