//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSNestedScrollViewPlugin\src\main\java\com\ashera\nestedscrollview\NestedScrollViewImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NestedScrollViewImpl")
#ifdef RESTRICT_NestedScrollViewImpl
#define INCLUDE_ALL_NestedScrollViewImpl 0
#else
#define INCLUDE_ALL_NestedScrollViewImpl 1
#endif
#undef RESTRICT_NestedScrollViewImpl

#if !defined (ASNestedScrollViewImpl_) && (INCLUDE_ALL_NestedScrollViewImpl || defined(INCLUDE_ASNestedScrollViewImpl))
#define ASNestedScrollViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASNestedScrollViewImpl_NestedScrollViewBean;
@class ASNestedScrollViewImpl_NestedScrollViewCommandBuilder;
@class ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder;
@class ASNestedScrollViewImpl_NestedScrollViewParamsBean;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASNestedScrollViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASNestedScrollViewImpl_NestedScrollViewBean *)getBean;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)getBuilder;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (ASNestedScrollViewImpl_NestedScrollViewParamsBean *)getParamsBean;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)getParamsBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (id)nativescrollViewCreate;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNestedScrollViewImpl)

inline NSString *ASNestedScrollViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNestedScrollViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNestedScrollViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASNestedScrollViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNestedScrollViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNestedScrollViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASNestedScrollViewImpl_init(ASNestedScrollViewImpl *self);

FOUNDATION_EXPORT ASNestedScrollViewImpl *new_ASNestedScrollViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNestedScrollViewImpl *create_ASNestedScrollViewImpl_init(void);

FOUNDATION_EXPORT void ASNestedScrollViewImpl_initWithNSString_(ASNestedScrollViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASNestedScrollViewImpl *new_ASNestedScrollViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNestedScrollViewImpl *create_ASNestedScrollViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASNestedScrollViewImpl_initWithNSString_withNSString_(ASNestedScrollViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASNestedScrollViewImpl *new_ASNestedScrollViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNestedScrollViewImpl *create_ASNestedScrollViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASNestedScrollViewImpl)

@compatibility_alias ComAsheraNestedscrollviewNestedScrollViewImpl ASNestedScrollViewImpl;

#endif

#if !defined (ASNestedScrollViewImpl_NestedScrollViewExt_) && (INCLUDE_ALL_NestedScrollViewImpl || defined(INCLUDE_ASNestedScrollViewImpl_NestedScrollViewExt))
#define ASNestedScrollViewImpl_NestedScrollViewExt_

#define RESTRICT_NestedScrollView 1
#define INCLUDE_ADXNestedScrollView 1
#include "NestedScrollView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASNestedScrollViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASNestedScrollViewImpl_NestedScrollViewExt : ADXNestedScrollView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASNestedScrollViewImpl:(ASNestedScrollViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNestedScrollViewImpl_NestedScrollViewExt)

FOUNDATION_EXPORT void ASNestedScrollViewImpl_NestedScrollViewExt_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl_NestedScrollViewExt *self, ASNestedScrollViewImpl *outer$);

FOUNDATION_EXPORT ASNestedScrollViewImpl_NestedScrollViewExt *new_ASNestedScrollViewImpl_NestedScrollViewExt_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNestedScrollViewImpl_NestedScrollViewExt *create_ASNestedScrollViewImpl_NestedScrollViewExt_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNestedScrollViewImpl_NestedScrollViewExt)

#endif

#if !defined (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder_) && (INCLUDE_ALL_NestedScrollViewImpl || defined(INCLUDE_ASNestedScrollViewImpl_NestedScrollViewCommandBuilder))
#define ASNestedScrollViewImpl_NestedScrollViewCommandBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandBuilder 1
#include "ViewGroupImpl.h"

@class ASNestedScrollViewImpl;

@interface ASNestedScrollViewImpl_NestedScrollViewCommandBuilder : ASViewGroupImpl_ViewGroupCommandBuilder

#pragma mark Public

- (instancetype)initWithASNestedScrollViewImpl:(ASNestedScrollViewImpl *)outer$;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)addAllModelWithId:(id)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)addModelByIndexWithId:(id)arg0
                                                                          withId:(id)arg1;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)addModelWithId:(id)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)animatorXmlWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)endAnimator;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)invalidate;

- (id)isMeasureAllChildren;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)removeModelAtIndexWithInt:(jint)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)removeModelByIdWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)requestLayout;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)reset;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setAddStatesFromChildrenWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setAnimateLayoutChangesWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setAnimateParentHierarchyWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setBottomWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setChildXmlWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setClipChildrenWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setClipToPaddingWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setElevationWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setFillViewportWithBoolean:(jboolean)value;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setForegroundGravityWithNSString:(NSString *)value;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setLayoutModeWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setLayoutTransitionDurationWithInt:(jint)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setLayoutTransitionWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setLeftWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setListitemWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setMeasureAllChildrenWithBoolean:(jboolean)value;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setModelDescPathWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setModelForWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setModelIdPathWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setNestedScrollingEnabledWithBoolean:(jboolean)value;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setOnAnimationCancelWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setOnAnimationEndWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setOnAnimationRepeatWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setOnAnimationStartWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setOnChildViewAddedWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setOnChildViewRemovedWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setOnScrollChangeWithNSString:(NSString *)value;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setOnSwipedWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setOutsideTouchableWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setPaddingBottomWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setPaddingEndWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setPaddingLeftWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setPaddingRightWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setPaddingStartWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setPaddingTopWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setPaddingWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setRightWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setSmoothScrollingEnabledWithBoolean:(jboolean)value;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setTopWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)startAnimator;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetAddStatesFromChildren;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetAlpha;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetBackground;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetBackgroundTint;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetBackgroundTintMode;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetBottom;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetClickable;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetClipChildren;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetClipToPadding;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetContentDescription;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetDuplicateParentState;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetEnabled;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetFocusable;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetForeground;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetForegroundGravity;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetForegroundTint;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetForegroundTintMode;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetId;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosAccessibilityHint;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosAccessibilityValue;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosAlpha;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosBackgroundColor;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosClipsToBounds;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosContentScaleFactor;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosIsFocused;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosIsHidden;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosIsOpaque;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosLargeContentImage;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosLargeContentTitle;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosTag;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosTintColor;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetKeepScreenOn;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetLayoutDirection;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetLayoutMode;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetLeft;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetLongClickable;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetMaxHeight;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetMaxWidth;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetMeasureAllChildren;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetMinHeight;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetMinWidth;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetModelDescPath;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetModelIdPath;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetModelParam;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetModelPojoToUi;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetModelSyncEvents;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetModelUiToPojo;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetPaddingBottom;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetPaddingEnd;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetPaddingLeft;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetPaddingRight;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetPaddingStart;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetPaddingTop;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetRight;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetRotation;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetRotationX;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetRotationY;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetScaleX;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetScaleY;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetSelected;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetTextAlignment;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetTextDirection;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetTop;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetTransformPivotX;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetTransformPivotY;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetTranslationX;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetTranslationY;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetTranslationZ;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetValidateForm;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)tryGetVisibility;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                                withId:(id)arg1;

- (ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNestedScrollViewImpl_NestedScrollViewCommandBuilder)

FOUNDATION_EXPORT void ASNestedScrollViewImpl_NestedScrollViewCommandBuilder_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *self, ASNestedScrollViewImpl *outer$);

FOUNDATION_EXPORT ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *new_ASNestedScrollViewImpl_NestedScrollViewCommandBuilder_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNestedScrollViewImpl_NestedScrollViewCommandBuilder *create_ASNestedScrollViewImpl_NestedScrollViewCommandBuilder_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNestedScrollViewImpl_NestedScrollViewCommandBuilder)

#endif

#if !defined (ASNestedScrollViewImpl_NestedScrollViewBean_) && (INCLUDE_ALL_NestedScrollViewImpl || defined(INCLUDE_ASNestedScrollViewImpl_NestedScrollViewBean))
#define ASNestedScrollViewImpl_NestedScrollViewBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupBean 1
#include "ViewGroupImpl.h"

@class ASNestedScrollViewImpl;
@protocol ASIWidget;

@interface ASNestedScrollViewImpl_NestedScrollViewBean : ASViewGroupImpl_ViewGroupBean

#pragma mark Public

- (instancetype)initWithASNestedScrollViewImpl:(ASNestedScrollViewImpl *)outer$;

- (id)isMeasureAllChildren;

- (void)setFillViewportWithBoolean:(jboolean)value;

- (void)setForegroundGravityWithNSString:(NSString *)value;

- (void)setMeasureAllChildrenWithBoolean:(jboolean)value;

- (void)setNestedScrollingEnabledWithBoolean:(jboolean)value;

- (void)setOnScrollChangeWithNSString:(NSString *)value;

- (void)setSmoothScrollingEnabledWithBoolean:(jboolean)value;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNestedScrollViewImpl_NestedScrollViewBean)

FOUNDATION_EXPORT void ASNestedScrollViewImpl_NestedScrollViewBean_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl_NestedScrollViewBean *self, ASNestedScrollViewImpl *outer$);

FOUNDATION_EXPORT ASNestedScrollViewImpl_NestedScrollViewBean *new_ASNestedScrollViewImpl_NestedScrollViewBean_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNestedScrollViewImpl_NestedScrollViewBean *create_ASNestedScrollViewImpl_NestedScrollViewBean_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNestedScrollViewImpl_NestedScrollViewBean)

#endif

#if !defined (ASNestedScrollViewImpl_NestedScrollViewParamsBean_) && (INCLUDE_ALL_NestedScrollViewImpl || defined(INCLUDE_ASNestedScrollViewImpl_NestedScrollViewParamsBean))
#define ASNestedScrollViewImpl_NestedScrollViewParamsBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupParamsBean 1
#include "ViewGroupImpl.h"

@class ASNestedScrollViewImpl;
@protocol ASIWidget;

@interface ASNestedScrollViewImpl_NestedScrollViewParamsBean : ASViewGroupImpl_ViewGroupParamsBean

#pragma mark Public

- (instancetype)initWithASNestedScrollViewImpl:(ASNestedScrollViewImpl *)outer$;

- (id)getLayoutGravityWithASIWidget:(id<ASIWidget>)w;

- (void)setLayoutGravityWithASIWidget:(id<ASIWidget>)w
                         withNSString:(NSString *)value;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNestedScrollViewImpl_NestedScrollViewParamsBean)

FOUNDATION_EXPORT void ASNestedScrollViewImpl_NestedScrollViewParamsBean_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl_NestedScrollViewParamsBean *self, ASNestedScrollViewImpl *outer$);

FOUNDATION_EXPORT ASNestedScrollViewImpl_NestedScrollViewParamsBean *new_ASNestedScrollViewImpl_NestedScrollViewParamsBean_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNestedScrollViewImpl_NestedScrollViewParamsBean *create_ASNestedScrollViewImpl_NestedScrollViewParamsBean_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNestedScrollViewImpl_NestedScrollViewParamsBean)

#endif

#if !defined (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder_) && (INCLUDE_ALL_NestedScrollViewImpl || defined(INCLUDE_ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder))
#define ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandParamsBuilder 1
#include "ViewGroupImpl.h"

@class ASNestedScrollViewImpl;

@interface ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder : ASViewGroupImpl_ViewGroupCommandParamsBuilder

#pragma mark Public

- (instancetype)initWithASNestedScrollViewImpl:(ASNestedScrollViewImpl *)outer$;

- (id)getLayoutGravity;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)reset;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)setLayoutGravityWithNSString:(NSString *)value;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)setLayoutMarginBottomWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)setLayoutMarginEndWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)setLayoutMarginHorizontalWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)setLayoutMarginLeftWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)setLayoutMarginRightWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)setLayoutMarginStartWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)setLayoutMarginTopWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)setLayoutMarginVerticalWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)setLayoutMarginWithNSString:(NSString *)arg0;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)tryGetLayoutGravity;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)tryGetLayoutMarginBottom;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)tryGetLayoutMarginEnd;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)tryGetLayoutMarginLeft;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)tryGetLayoutMarginRight;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)tryGetLayoutMarginStart;

- (ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *)tryGetLayoutMarginTop;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder)

FOUNDATION_EXPORT void ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *self, ASNestedScrollViewImpl *outer$);

FOUNDATION_EXPORT ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *new_ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder *create_ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNestedScrollViewImpl_NestedScrollViewCommandParamsBuilder)

#endif

#if !defined (ASNestedScrollViewImpl_MyUIScrollViewDelegate_) && (INCLUDE_ALL_NestedScrollViewImpl || defined(INCLUDE_ASNestedScrollViewImpl_MyUIScrollViewDelegate))
#define ASNestedScrollViewImpl_MyUIScrollViewDelegate_

@class ASNestedScrollViewImpl;

@interface ASNestedScrollViewImpl_MyUIScrollViewDelegate : NSObject {
 @public
  jint oldScrollY_;
  jint oldScrollX_;
}

#pragma mark Public

- (instancetype)initWithASNestedScrollViewImpl:(ASNestedScrollViewImpl *)outer$;

- (void)nativeScrollChangeListenerWithId:(id)nativeWidget;

- (void)onscrollWithInt:(jint)scrollX
                withInt:(jint)scrollY;

#pragma mark Package-Private

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNestedScrollViewImpl_MyUIScrollViewDelegate)

FOUNDATION_EXPORT void ASNestedScrollViewImpl_MyUIScrollViewDelegate_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl_MyUIScrollViewDelegate *self, ASNestedScrollViewImpl *outer$);

FOUNDATION_EXPORT ASNestedScrollViewImpl_MyUIScrollViewDelegate *new_ASNestedScrollViewImpl_MyUIScrollViewDelegate_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNestedScrollViewImpl_MyUIScrollViewDelegate *create_ASNestedScrollViewImpl_MyUIScrollViewDelegate_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNestedScrollViewImpl_MyUIScrollViewDelegate)

#endif

#pragma pop_macro("INCLUDE_ALL_NestedScrollViewImpl")
