//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSNestedScrollViewPlugin\src\main\java\com\ashera\nestedscrollview\NestedScrollViewImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NestedScrollViewImpl")
#ifdef RESTRICT_NestedScrollViewImpl
#define INCLUDE_ALL_NestedScrollViewImpl 0
#else
#define INCLUDE_ALL_NestedScrollViewImpl 1
#endif
#undef RESTRICT_NestedScrollViewImpl

#if !defined (ASNestedScrollViewImpl_) && (INCLUDE_ALL_NestedScrollViewImpl || defined(INCLUDE_ASNestedScrollViewImpl))
#define ASNestedScrollViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASNestedScrollViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(int32_t)index;

- (id)asNativeWidget;

- (id)asWidget;

- (bool)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (id)nativescrollViewCreate;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (bool)removeWithInt:(int32_t)index;

- (bool)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(bool)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNestedScrollViewImpl)

inline NSString *ASNestedScrollViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNestedScrollViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNestedScrollViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASNestedScrollViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNestedScrollViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNestedScrollViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASNestedScrollViewImpl_init(ASNestedScrollViewImpl *self);

FOUNDATION_EXPORT ASNestedScrollViewImpl *new_ASNestedScrollViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNestedScrollViewImpl *create_ASNestedScrollViewImpl_init(void);

FOUNDATION_EXPORT void ASNestedScrollViewImpl_initWithNSString_(ASNestedScrollViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASNestedScrollViewImpl *new_ASNestedScrollViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNestedScrollViewImpl *create_ASNestedScrollViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASNestedScrollViewImpl_initWithNSString_withNSString_(ASNestedScrollViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASNestedScrollViewImpl *new_ASNestedScrollViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNestedScrollViewImpl *create_ASNestedScrollViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASNestedScrollViewImpl)

@compatibility_alias ComAsheraNestedscrollviewNestedScrollViewImpl ASNestedScrollViewImpl;


#endif

#if !defined (ASNestedScrollViewImpl_NestedScrollViewExt_) && (INCLUDE_ALL_NestedScrollViewImpl || defined(INCLUDE_ASNestedScrollViewImpl_NestedScrollViewExt))
#define ASNestedScrollViewImpl_NestedScrollViewExt_

#define RESTRICT_NestedScrollView 1
#define INCLUDE_ADXNestedScrollView 1
#include "NestedScrollView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASNestedScrollViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASNestedScrollViewImpl_NestedScrollViewExt : ADXNestedScrollView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASNestedScrollViewImpl:(ASNestedScrollViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (int32_t)getMaxHeight;

- (int32_t)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(int32_t)offset;

- (void)offsetTopAndBottomWithInt:(int32_t)offset;

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(int32_t)height;

- (void)setMaxWidthWithInt:(int32_t)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(int32_t)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNestedScrollViewImpl_NestedScrollViewExt)

FOUNDATION_EXPORT void ASNestedScrollViewImpl_NestedScrollViewExt_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl_NestedScrollViewExt *self, ASNestedScrollViewImpl *outer$);

FOUNDATION_EXPORT ASNestedScrollViewImpl_NestedScrollViewExt *new_ASNestedScrollViewImpl_NestedScrollViewExt_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNestedScrollViewImpl_NestedScrollViewExt *create_ASNestedScrollViewImpl_NestedScrollViewExt_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNestedScrollViewImpl_NestedScrollViewExt)


#endif

#if !defined (ASNestedScrollViewImpl_MyUIScrollViewDelegate_) && (INCLUDE_ALL_NestedScrollViewImpl || defined(INCLUDE_ASNestedScrollViewImpl_MyUIScrollViewDelegate))
#define ASNestedScrollViewImpl_MyUIScrollViewDelegate_

@class ASNestedScrollViewImpl;
@class JavaLangInteger;

@interface ASNestedScrollViewImpl_MyUIScrollViewDelegate : NSObject {
 @public
  int32_t oldScrollY_;
  int32_t oldScrollX_;
}

#pragma mark Public

- (instancetype)initWithASNestedScrollViewImpl:(ASNestedScrollViewImpl *)outer$;

- (void)nativeScrollChangeListenerWithId:(id)nativeWidget;

- (void)onscrollWithInt:(int32_t)scrollX
                withInt:(int32_t)scrollY;

#pragma mark Package-Private

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNestedScrollViewImpl_MyUIScrollViewDelegate)

FOUNDATION_EXPORT void ASNestedScrollViewImpl_MyUIScrollViewDelegate_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl_MyUIScrollViewDelegate *self, ASNestedScrollViewImpl *outer$);

FOUNDATION_EXPORT ASNestedScrollViewImpl_MyUIScrollViewDelegate *new_ASNestedScrollViewImpl_MyUIScrollViewDelegate_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNestedScrollViewImpl_MyUIScrollViewDelegate *create_ASNestedScrollViewImpl_MyUIScrollViewDelegate_initWithASNestedScrollViewImpl_(ASNestedScrollViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNestedScrollViewImpl_MyUIScrollViewDelegate)


#endif

#pragma pop_macro("INCLUDE_ALL_NestedScrollViewImpl")
