//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSNestedScrollViewPlugin\src\main\java\com\ashera\nestedscrollview\NestedScrollViewPlugin.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NestedScrollViewPlugin")
#ifdef RESTRICT_NestedScrollViewPlugin
#define INCLUDE_ALL_NestedScrollViewPlugin 0
#else
#define INCLUDE_ALL_NestedScrollViewPlugin 1
#endif
#undef RESTRICT_NestedScrollViewPlugin

#if !defined (ASNestedScrollViewPlugin_) && (INCLUDE_ALL_NestedScrollViewPlugin || defined(INCLUDE_ASNestedScrollViewPlugin))
#define ASNestedScrollViewPlugin_

@interface ASNestedScrollViewPlugin : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)initPlugin OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNestedScrollViewPlugin)

FOUNDATION_EXPORT void ASNestedScrollViewPlugin_init(ASNestedScrollViewPlugin *self);

FOUNDATION_EXPORT ASNestedScrollViewPlugin *new_ASNestedScrollViewPlugin_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNestedScrollViewPlugin *create_ASNestedScrollViewPlugin_init(void);

FOUNDATION_EXPORT void ASNestedScrollViewPlugin_initPlugin(void);

J2OBJC_TYPE_LITERAL_HEADER(ASNestedScrollViewPlugin)

@compatibility_alias ComAsheraNestedscrollviewNestedScrollViewPlugin ASNestedScrollViewPlugin;


#endif

#pragma pop_macro("INCLUDE_ALL_NestedScrollViewPlugin")
